"""add appointments table

Revision ID: 3967b09565c8
Revises: 6ec63c8db68e
Create Date: 2026-07-20 14:58:14.830794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3967b09565c8'
down_revision = '6ec63c8db68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('appointment_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###
