"""add patients && appointments tables

Revision ID: 6e332f3e5087
Revises: 3967b09565c8
Create Date: 2026-07-20 15:18:17.916531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e332f3e5087'
down_revision = '3967b09565c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
