"""add table changes

Revision ID: ff04eb8e2e2f
Revises: 6a4082367ecc
Create Date: 2026-07-28 22:31:59.983151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff04eb8e2e2f'
down_revision = '6a4082367ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_doctors_phone'), ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_doctors_phone'), type_='unique')

    # ### end Alembic commands ###
